[package]
name = "models"
version = "0.0.1"
edition = "2018"
license = "Apache 2.0"
description = "Future migration management library for applications using a database"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
