[package]
name = "sqlx-models"
version = "0.1.0"
edition = "2018"

[features]
migrations = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dotenv = "0.15.0"
log = "0.4.14"
sqlx-models-parser = { path = "../sqlx-models-parser" }
sqlx = "0.5.5"
url = "2.2.2"
sqlx-models-proc-macro = { path = "../sqlx-models-proc-macro" }
chrono = "0.4.19"
fehler = "1.0.0"
sqlformat = "0.1.7"
once_cell = "1.8.0"

[dev-dependencies]
sqlx = { version = "0.5.7", features = ["any", "runtime-tokio-native-tls"] }
