[package]
name = "sqlx-models-proc-macro"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.28"
quote = "1.0.9"
sqlx-models-parser = "0.0.1"
syn = "1.0.74"
