[package]
name = "models"
version = "0.0.1"
edition = "2018"
license = "Apache-2.0"
description = "Future migration management library for applications using a database"
readme = "../README.md"

[features]
default = ["sqlformat"]
postgres = []
sqlx = []
rusqlite = []
tokio_postgres = []
# serde features
json = []
binary = []


[dependencies]
thiserror = "1.0.29"
itertools = "0.10.1"
models-parser = { path = "../models-parser" }
once_cell = "1.8.0"
url = "2.2.2"
topological-sort = "0.1.0"
sqlformat = { version = "0.1.8", optional = true }
chrono = {version = "0.4.19", optional = true }